version: '3'
services:
  notebook:
    container_name: python_notebook
    labels:
      name: jupyter notebook
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/src
      - ./data:/home/data
    build: .